// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Image struct {
	ID   string `json:"id"`
	Path string `json:"path"`
}

type Product struct {
	ID            string   `json:"id"`
	Name          string   `json:"name"`
	Stock         int      `json:"stock"`
	Description   string   `json:"description"`
	OriginalPrice float64  `json:"originalPrice"`
	ComparePrice  float64  `json:"comparePrice"`
	Images        []*Image `json:"images"`
	Created       int      `json:"created"`
}
